# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f050c6591a7d9de762dd3f3686f6f61fc990b137c90fe4c00aa1cccfdd8c2706622bac85a9e8956df7961cc414e5cd4cfc3d5760465c9bd9346a4b43f9bca2b2

test:
  secret_key_base: cc1ef9b7b3d22d970ebc9b786e421e8ef8c18bc71df902f1b20f724e9bd0ba1ae0e6eb72c17bb53845ced2a4ab89dccdccd6526d02a5f25bbf322f8d7e9735d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
